### ISSUE TITLE
Production import error when using .scss file with styleUrls property

### ISSUE THREAD

**Issue by jedmundo** [ghpabs/angular2-seed-project#70] opened 2016-03-19 15:54 UTC
Hello,

I am using the following directory structure:

scripts
- login
-- login.component.ts
-- login.scss
scss
- variables.scss

Thing is when I compile my login.scss I need to import the variables so Im using:
@import("../../scss/variables")

If I dont use this import it returns an error during compile time of scss (every time I run "gulp build serve")

In development this works. But when I build for production the statement "@import("../../scss/variables")" returns 404.

My login.component.ts contains:
@Component({
    selector: 'login',
    templateUrl: './login.html',
    styleUrls: ['./login.scss']
})

- Node Version: `5.9.0`
- NPM Version: `3.7.3`
- Gulp CLI version: `0.4.0`
- Typings version: `0.7.9`

**Comment by ghpabs** [comment] 2016-03-20 13:23
Cool thanks for reporting it - I think it's related to the plugin [`gulp-inline-ng2-template`](https://github.com/ludohenin/gulp-inline-ng2-template) but I need to investigate it further.

**Comment by ghpabs** [comment] 2016-03-21 09:50
Yeah it looks like `gulp-inline-ng2-template` can't resolve variables.

![image](https://cloud.githubusercontent.com/assets/3250667/13915033/1e69d388-ef4a-11e5-9167-dacac7ddbaff.png)

I'll raise an issue with the team over there and see what they think.

**Comment by ghpabs** [comment] 2016-03-21 10:03
I'm actually going to close this issue as it's not a bug, but a feature currently not supported by a third-party library.

You can see the feature request ticket here: https://github.com/ludohenin/gulp-inline-ng2-template/issues/28

**Closed by ghpabs** 2016-03-21 10:03 UTC

**Comment by jedmundo** [comment] 2016-03-21 10:10
Ok, thanks alot!

**Comment by ghpabs** [comment] 2016-03-21 10:12
Okay cool - sorry I couldn't be of much help.
